import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { renderShell } from "../routes/ui.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
assert.equal(manifest.id, "finance-workbench");
assert.equal(manifest.minAppVersion, "0.0.4");
assert.equal(manifest.trust, "full-access");
assert.deepEqual(manifest.network.allowedHosts, ["fuyao.aicubes.cn"]);
assert.equal(manifest.ui.hostCapabilities.includes("external.open"), false);
assert.equal(manifest.contributes.page.route, "/page");
assert.equal(manifest.contributes.widget.route, "/widget");
assert.doesNotMatch(manifest.contributes.page.icon, /<svg/i);
for (const file of ["index.js", "routes/api.js", "routes/ui.js", "assets/panel.js", "assets/panel.css"]) assert.ok(fs.existsSync(path.join(root, file)) && fs.statSync(path.join(root, file)).size > 0, `${file} must exist`);
const toolFiles = fs.readdirSync(path.join(root, "tools")).filter((name) => name.endsWith(".js"));
const toolNames = [];
for (const file of toolFiles) toolNames.push((await import(path.join(root, "tools", file))).name);
assert.deepEqual(toolNames.sort(), ["backtest_run", "export_report", "monitor_create", "portfolio_query", "research_public"]);
assert.equal(toolNames.some((name) => /trade|order|broker|buy|sell/.test(name)), false);
const shell = renderShell({ req: { query: () => "" } }, { pluginId: manifest.id }, "page");
for (const relative of [...shell.matchAll(/\/assets\/(panel\.(?:js|css))/g)].map((match) => match[1])) assert.ok(fs.existsSync(path.join(root, "assets", relative)), `shell asset ${relative} must exist`);
const browserSource = fs.readFileSync(path.join(root, "ui/Panel.tsx"), "utf8");
assert.doesNotMatch(browserSource, /hithinkApiKey|fuyao\.aicubes\.cn|X-api-key/i);
assert.match(browserSource, /hana\.ready\(\)/);
const applicationSource = fs.readFileSync(path.join(root, "src/application.js"), "utf8");
assert.match(applicationSource, /hithink-market-dump[\s\S]*status: "blocked"/);
assert.doesNotMatch(applicationSource, /child_process|spawn\(|exec\(|python|marketdb/i);
await import(path.join(root, "index.js"));
await import(path.join(root, "routes/api.js"));
console.log(`finance-workbench package verified: ${toolFiles.length} tools, page+widget assets present, no trading surface`);
